import os
from gtts import gTTS

# Create the mp3 folder if it doesn't exist
if not os.path.exists("mp3"):
    os.makedirs("mp3")

# List of paragraphs to convert to speech
texts = [
    "When it comes to pets, there are often two favourites, dogs and cats. Dogs are known for their loyalty, companionship and high energy, always seeking attention and playtime. They form a strong bond with their owners, providing affection and protection. Cats on the other hand, are known for being low-maintenance and independent, requiring less supervision and care. They are known for their calm demeanor, and while they may not seek constant attention, they show affection in their own way. So the question is, which makes the better pet?",
    "Here’s a question that sparks quite a bit of debate: does pineapple belong on pizza? Some argue that it’s a unique and delicious combination, blending sweet and savory in a way that actually works. They enjoy the contrast of flavours and the unexpected twist it brings. Others, however, believe that fruit has no place on pizza, insisting that it messes with the traditional savory experience. It’s a conversation that divides pizza lovers everywhere. So, at the end of the day, is pineapple an acceptable topping for pizza?",
    "People often debate whether Formula 1 is truly a sport. On one hand, it demands a remarkable level of physical endurance from its drivers, who must stay in peak physical condition to endure the extreme g-forces and maintain focus throughout the race. On the other hand, many argue that the cars and the advanced technology behind them play a bigger role than the athletes themselves, leading some to question if it’s more about engineering than athleticism. So, is F1 a legitimate sport?",
    "Rugby and tennis are both physically demanding sports, but they challenge athletes differently. Rugby involves constant physical contact, requiring strength, endurance, and teamwork. Players need to be tough and resilient, often pushing their bodies to the limit. In contrast, tennis relies heavily on speed, agility, and mental focus. It tests a player’s stamina as they go through long, intense rallies. So, when it comes to physical demands, which sport is more challenging: rugby or tennis?",
    "The debate over school uniforms has been ongoing for years. Supporters argue that uniforms promote equality by eliminating fashion distractions, allowing students to focus on education and creating a professional atmosphere. They believe uniforms help reduce peer pressure and bullying. Critics, however, argue that uniforms suppress creativity and self-expression, suggesting students should be free to express their individuality through fashion. So, should schools implement uniforms, or allow students to dress as they wish?",
    "Many of our favorite movies are based on books, but often, the adaptation doesn’t fully capture the original. Books offer depth and detail that films sometimes miss, providing a richer experience. Movies, however, bring stories to life with visuals, sound, and pacing, creating an immersive experience words can’t match. They make characters and scenes come alive in ways books can’t. So, which is better: the book that fuels your imagination, or the movie that brings the story to life on screen?",
    "We’re taught that honesty is the best policy, but are there times when lying might be necessary? Some argue that honesty, no matter how difficult, is always the right choice. Others, however, believe that certain lies can be necessary for maintaining harmony, protecting someone’s feelings, or avoiding unnecessary conflict. They argue that sometimes a small, well-intentioned lie can serve a greater good. So, should we always aim to tell the truth, or are some white lies acceptable to protect others?",
    "Climbing a mountain and running a marathon are both intense physical challenges, but they test the body in different ways. Climbing requires strength, endurance, and the ability to handle extreme conditions like altitude, cold weather, and rough terrain. It’s a test of both physical power and mental toughness. Running a marathon, on the other hand, demands cardiovascular endurance and the mental toughness to push through pain and exhaustion over long distances. So, which is more demanding: scaling a mountain or running a marathon?",
    "When it comes to choosing where to live, the decision often depends on the lifestyle each environment offers. City living provides convenience, excitement, and career opportunities, but it can also be stressful with noise, crowds, and a fast pace. The countryside, in contrast, offers peace, space, and a slower pace of life, though it lacks the amenities and social scene of the city. So, which do you prefer—the fast-paced energy of city life or the tranquility of the countryside?",
    "When it comes to being productive, everyone has their own time of day when they feel most focused and energized. Some people love the peaceful quiet of early mornings, using the calm to get a head start and feel productive. Others thrive at night, when everything is quieter, and they can concentrate deeply without distractions. Whether it’s the fresh start of a new day or the stillness of the night, each time has its own unique appeal. So, are you someone who feels most energized at the crack of dawn, or do you get your best ideas late at night?",
    "Have you ever wondered what it would be like to have a superpower? Imagine being able to fly, soaring above the world, feeling the wind rush as you explore the sky. The freedom to go anywhere and see the world from a new perspective would be incredible. Or imagine being invisible, experiencing everything around you without anyone noticing. You could move undetected, observe the world from the shadows, and gather information without detection. Both powers offer amazing advantages, so, which would you choose: flying or invisibility?",
    "People go on vacation for many reasons. Some people crave an action-packed trip filled with adventure, eager to explore new places, try exciting activities, and experience the thrill of discovery. Others, however, prefer a peaceful getaway to relax, recharge, and escape from the hustle and bustle. So, which do you think is better, an adventurous vacation or relaxing retreat?",
    "Penalty shootouts are one of the most dramatic moments in sports, often deciding major games when the score is tied. Some argue they’re a fair test of skill and nerves, adding excitement to the game’s conclusion. Others feel they’re too reliant on luck and don’t reflect the overall performance of the teams. So, are penalty shootouts a thrilling and fair way to determine a winner, or should there be a better solution?",
    "Footballers earn millions every year, which seems like a lot for kicking a ball around. But then, their games bring in huge audiences, and the teams they play for make massive amounts of money from sponsorships, merchandise, and broadcasting deals. So, do footballers really get paid too much, or are their salaries just a reflection of the money the sport generates?",
    "When it comes to tea in Ireland, the debate often comes down to two brands Barry’s and Lyons. Barry’s fans argue that their tea is stronger and more flavorful, making it the perfect choice for a cup of comfort. On the other hand, Lyons enthusiasts swear by its smooth, balanced taste that’s perfect for any time of the day. Both brands have loyal followings, but which is truly the superior Barry’s or Lyons?",
    "Winter and summer both have their own charm, but which is truly better? Winter brings cozy nights by the fire, and festivities, while summer offers sunshine, outdoor adventures, and the chance to relax on a beach. Winter lovers enjoy the cold, crisp air, while summer enthusiasts look forward to long days and warm nights. So, which do you think is the better season, winter or summer?",
    "Hot drinks, like tea, coffee, and hot chocolate, bring comfort, warmth, and a sense of relaxation, especially during colder months.. Cold drinks, on the other hand, are refreshing, energizing, and perfect for hot weather, with options like iced tea, smoothies, and chilled coffee. So, which is better: warm or hot drinks?",
    "Lidl and Aldi are both discount supermarkets known for their great deals, but which one truly offers the best shopping experience? Lidl is famous for its fresh bakery items and wide variety of European products, while Aldi is praised for its efficiency and even lower prices. Some say Aldi’s no-frills approach makes it quicker and easier to shop, while Lidl’s product variety gives it the edge. Which is your go-to, Lidl or Aldi?",
    "AI art has gained popularity for its ability to create stunning visuals quickly, but does it carry the same value and meaning as art made by humans? Supporters of AI art praise its efficiency, innovation, and creativity, while others argue that true art comes from the human experience, emotion, and skill. So, which do you think holds more value: art created by AI or human hands?",
    "Supporters of same-sex schools argue that separating genders helps students focus and perform better, especially in subjects traditionally dominated by one gender. On the other hand, people believe that mixed-gender education better prepares students for real-world interactions in both the workplace and society. So, should same-sex schools continue, or should all schools be co-ed?",
    "Private schools often offer smaller class sizes, specialized programs, and more resources than public schools. However, critics argue they create inequality by relying on a family’s ability to pay. Supporters believe private schools offer more choice and a higher standard of education. So, should private schools continue, or should the focus be on improving public schools for everyone?",
    "Some argue that 16-year-olds are mature enough to make informed decisions, as they are affected by political issues like education and employment. Lowering the voting age could also boost political engagement among young people. However, others believe 16-year-olds lack the life experience to vote responsibly. So, should the voting age be lowered to 16, or remain at 18 to ensure voters are fully prepared?"
]

# Convert each text to a separate audio file
for i, text in enumerate(texts, start=1):
    myobj = gTTS(text=text, lang='en', slow=False)
    filename = f"mp3/Audio{i}.mp3"  # Save to the 'mp3' folder
    myobj.save(filename)
    print(f"Saved {filename}")
