import os
from gtts import gTTS

# Create the mp3 folder if it doesn't exist
if not os.path.exists("mp3"):
    os.makedirs("mp3")

# List of paragraphs to convert to speech
texts = [
    "When it comes to pets, there are often two favorites, dogs or cats. Dogs are known for their loyalty, companionship, and energy, often forming deep connections with their owners. On the other hand, cats offer independence, low-maintenance care, and a more subtle form of affection. Both have their unique qualities, so the real question is: which makes the better pet?",
    "Here’s a question that sparks quite a bit of debate, should pineapple be considered an acceptable topping on pizza? Some argue that it’s an unexpected but delicious combination, blending sweet and savory in a way that works. Others, however, feel that fruit simply has no place on pizza. It’s a conversation that divides pizza lovers, but at the end of the day, is pineapple a welcome addition or an unnecessary twist on tradition?",
    "People often debate if Formula 1 is a sport or not. On one hand, it requires an intense level of physical endurance from drivers, who must maintain a peak level of fitness to withstand the g-forces. On the other hand, many argue that the cars and technology take on a larger role than the athletes themselves. So, is F1 a sport or a high-tech spectacle driven by engineering?",
    "Rugby and tennis are both physically demanding sports, but in different ways. Rugby requires constant physical contact, strength, endurance and teamwork. Tennis, on the other hand, requires speed, agility, and mental focus, often testing a player’s endurance and stamina. So, which sport is more demanding: rugby, or tennis?",
    "The debate over school uniforms has been ongoing for years. Supporters argue that uniforms promote equality, focusing on education rather than fashion, leading to a more professional environment. Others believe they stifle creativity and self-expression, believing students should be free to express their individuality. So, should schools have uniforms or let students dress how they like?",
    "Many of our favorite movies are based on books, but often, the adaptation doesn’t quite live up to the original. Books provide depth and detail that movies sometimes skip, while movies bring stories to life with visuals and pacing, immersing you in a way words on a page can’t. Which is better: the book that allows your imagination to run wild, or the movie that brings a story to life on the screen?",
    "We’re taught that honesty is the best policy, but are there times when lying might be necessary? Some argue that honesty, no matter how difficult, is always the right choice, while others believe that certain lies are necessary for maintaining harmony or protecting others. So, should we always tell the truth, or are some white lies acceptable to avoid hurting feelings or causing conflict?",
    "Climbing a mountain and running a marathon are both intense physical challenges, but in very different ways. Climbing a mountain requires strength, endurance, and the ability to handle extreme conditions like altitude and weather. Running a marathon, on the other hand, demands cardiovascular endurance and the mental fortitude to keep going, often through pain and exhaustion. So, which one is harder?",
    "City living offers convenience, excitement, and career opportunities, but it can be stressful with noise and crowds. The countryside, on the other hand, provides peace, space, and a slower pace of life, though it lacks the amenities and social scene of the city. So, which do you prefer—the fast-paced city life or the calm of the countryside?",
    "Some people love the quiet of early mornings, using the calm to get a head start and feel productive. Others thrive at night, when everything is quieter and they can focus without distractions. Are you someone who feels most energized at the crack of dawn, or do you get your best ideas late at night? Which do you think is the better time for productivity—early mornings or late nights?",
    "Have you ever wondered what it would be like to have a superpower? Imagine being able to fly, soaring above the world, or being invisible, experiencing everything without anyone noticing. Flying lets you explore the world from a new perspective, while invisibility offers the chance to observe without being seen. Both powers come with unique advantages so, which would you choose: flying or invisibility?",
    "People go on vacation for many reasons. Some people crave an action-packed trip filled with adventure and sightseeing, eager to explore new places and try new activities. Others, however, prefer a peaceful getaway to relax, recharge, and escape from the hustle and bustle. So, which do you think is better, an adventurous vacation or relaxing retreat?",
    "Penalty shootouts are one of the most dramatic moments in sports, often deciding major games when the score is tied. Some argue they’re a fair test of skill and nerves, adding excitement to the game’s conclusion. Others feel they’re too reliant on luck and don’t reflect the overall performance of the teams. So, are penalty shootouts a thrilling and fair way to determine a winner, or should there be a better solution?",
    "Footballers earn millions every year, which seems like a lot for kicking a ball around. But then, their games bring in huge audiences, and the teams they play for make massive amounts of money from sponsorships, merchandise, and broadcasting deals. So, do footballers really get paid too much, or are their salaries just a reflection of the money the sport generates?",
    "When it comes to tea in Ireland, the debate often comes down to two brands Barry’s and Lyons. Barry’s fans argue that their tea is stronger and more flavorful, making it the perfect choice for a cup of comfort. On the other hand, Lyons enthusiasts swear by its smooth, balanced taste that’s perfect for any time of the day. Both brands have loyal followings, but which is truly the superior Barry’s or Lyons?",
    "Winter and summer both have their own charm, but which is truly better? Winter brings cozy nights by the fire, and festivities, while summer offers sunshine, outdoor adventures, and the chance to relax on a beach. Winter lovers enjoy the cold, crisp air, while summer enthusiasts look forward to long days and warm nights. So, which do you think is the better season, winter or summer?",
    "Hot drinks, like tea, coffee, and hot chocolate, bring comfort, warmth, and a sense of relaxation, especially during colder months.. Cold drinks, on the other hand, are refreshing, energizing, and perfect for hot weather, with options like iced tea, smoothies, and chilled coffee. So, which is better: warm or hot drinks?",
    "Lidl and Aldi are both discount supermarkets known for their great deals, but which one truly offers the best shopping experience? Lidl is famous for its fresh bakery items and wide variety of European products, while Aldi is praised for its efficiency and even lower prices. Some say Aldi’s no-frills approach makes it quicker and easier to shop, while Lidl’s product variety gives it the edge. Which is your go-to, Lidl or Aldi?",
    "AI art has gained popularity for its ability to create stunning visuals quickly, but does it carry the same value and meaning as art made by humans? Supporters of AI art praise its efficiency, innovation, and creativity, while others argue that true art comes from the human experience, emotion, and skill. So, which do you think holds more value: art created by AI or human hands?",
    "Supporters of same-sex schools argue that separating genders helps students focus and perform better, especially in subjects traditionally dominated by one gender. On the other hand, people believe that mixed-gender education better prepares students for real-world interactions in both the workplace and society. So, should same-sex schools continue, or should all schools be co-ed?",
    "Private schools often offer smaller class sizes, specialized programs, and more resources than public schools. However, critics argue they create inequality by relying on a family’s ability to pay. Supporters believe private schools offer more choice and a higher standard of education. So, should private schools continue, or should the focus be on improving public schools for everyone?",
    "Some argue that 16-year-olds are mature enough to make informed decisions, as they are affected by political issues like education and employment. Lowering the voting age could also boost political engagement among young people. However, others believe 16-year-olds lack the life experience to vote responsibly. So, should the voting age be lowered to 16, or remain at 18 to ensure voters are fully prepared?"
]

# Convert each text to a separate audio file
for i, text in enumerate(texts, start=1):
    myobj = gTTS(text=text, lang='en', slow=False)
    filename = f"mp3/Audio{i}.mp3"  # Save to the 'mp3' folder
    myobj.save(filename)
    print(f"Saved {filename}")
